[package]
name = "aoc2021"
version = "0.1.0"
authors = ["Erik Silfverswärd <erik@silfversward.se>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "^0.10"
ndarray = "^0.15"
bitvec = "1"
funty = "2"
